<?php

namespace Database\Seeders;

use App\Models\Booth;
use App\Models\Company;
use Illuminate\Database\Seeder;

class BoothSeeder extends Seeder
{
    public function run(): void
    {
        $companies = Company::all();
        
        $booths = [
            [
                'name' => 'Booth Gold 1',
                'size' => '3x3 meter',
                'facility' => 'Meja, kursi, listrik, wifi',
                'price' => 5000000,
                'picture' => 'booth_a1.jpg',
                'status' => 'booked',
                'company_id' => $companies->first()?->id,
            ],
            [
                'name' => 'Booth Gold 2',
                'size' => '3x3 meter',
                'facility' => 'Meja, kursi, listrik, wifi',
                'price' => 5000000,
                'picture' => 'booth_a2.jpg',
                'status' => 'booked',
                'company_id' => $companies->skip(1)->first()?->id,
            ],
            [
                'name' => 'Booth Gold 3',
                'size' => '4x4 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor',
                'price' => 7500000,
                'picture' => 'booth_b1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Gold 4',
                'size' => '4x4 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor',
                'price' => 7500000,
                'picture' => 'booth_b2.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Gold 5',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Gold 6',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Gold 7',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Gold 8',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Silver 1',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Silver 2',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Silver 3',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Silver 4',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Silver 5',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Silver 6',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Platinum 1',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Platinum 2',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Platinum 3',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Platinum 4',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Platinum 5',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Platinum 6',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Platinum 7',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Platinum 8',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Bronze 1',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Bronze 2',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Bronze 3',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Bronze 4',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Bronze 5',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Bronze 6',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Bronze 7',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Bronze 8',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
            [
                'name' => 'Booth Bronze 9',
                'size' => '5x5 meter',
                'facility' => 'Meja, kursi, listrik, wifi, proyektor, sound system',
                'price' => 10000000,
                'picture' => 'booth_premium1.jpg',
                'status' => 'available',
                'company_id' => null,
            ],
        ];

        foreach ($booths as $booth) {
            Booth::create($booth);
        }
    }
}